
import { inter } from '@/app/ui/fonts'
import "@/app/globals.css";
import Image from 'next/image';
import  Header from '@/app/components/header'
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import Link from 'next/link';



export const metadata = {
  title: "Ejemplos Crypto para Curso Intro a la Blockchain - RU",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col  min-h-screen`}>
        <Header />
        <main className="flex-grow w-full">
          <ToastContainer />
          {children}
        </main>
        <footer className="w-full py-2  text-xs inset space-y-2">
          <div className="flex justify-center space-x-2">
          <img
            src="/github-mark.svg" 
            alt="GitHub Logo"
            width={16} 
            height={16} 
          />
            <Link  href='https://github.com/RoberVH/trivias-contract-solidity' target="_blank" rel="noopener noreferrer" className="flex items-center">
              <span className="underline">Contrato</span>
            </Link>
            <Link  href='https://github.com/RoberVH/crypto-ts-app' target="_blank" rel="noopener noreferrer" className="flex items-center">
            <span className="underline">Aplicación</span>
            </Link>
          </div>
          <div className=" flex items-center justify-center">

          <Link href='https://x.com/RoberVH' target="_blank" rel="noopener noreferrer" className="flex items-center">
          <Image
              src="/x.svg"
              alt="X (Twitter) icon"
              width={16}
              height={16}
              className="mr-2 flex items-center"
              />
          </Link>
          <Link href='https://www.linkedin.com/in/roberto-vicuna/' target="_blank" rel="noopener noreferrer" className="flex items-center">
          <Image
              src="/linkedin.svg"
              alt="LinkedIn icon"
              width={15}
              height={15}
              className="mr-2 flex items-center"
          />
          </Link>
            <span className="">
              Roberto Vicuña 
            </span>
            <span>| rovicher.eth | ©2024</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
