
import { inter } from '@/app/ui/fonts'
import "./globals.css";
import  Header from '@/app/components/header'


export const metadata = {
  title: "Ejemplos Crypto para Curso Intro a la Blockchain - RU",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Header/>
        {children}
        </body>
    </html>
  );
}
